name: Release npm package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      # Checkout branch
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # Setup node environment
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      # Dry run a release to check if one if necessary
      - name: Check for new release
        uses: cycjimmy/semantic-release-action@v2.5.0
        id: dry_release
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Get modules from cache
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Build site
      - name: Build site
        run: |
          npm ci
          VERSION_NUMBER=$VERSION_NUMBER npm run build:all
        env:
          VERSION_NUMBER: ${{ steps.dry_release.outputs.new_release_version }}
      # Publish the release IF the version number is being changed
      - name: Publish package
        if: steps.dry_release.outputs.new_release_published == 'true'
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMVER_GITHUB_TOKEN }}
